
name: Python Package

on:
  release:
  pull_request:

jobs:
  deploy:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          - os: windows-latest
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check --output-format=github .
      continue-on-error: true
      
    - name: Test with pytest
      run: |
        poetry run py.test --cov-append
